// Copyright (c) 2026 TXCSL. Licensed under the MIT License.

#pragma once
#include "impl/basic_utils.hpp"
#include "impl/csl/definition.hpp"
#include "impl/csl/compiler.hpp"
#include "impl/csl/compiler_bracket_parser.hpp"
#include "impl/csl/compiler_tokenlizer.hpp"

namespace tx::csl {
// this class used to be called as `Compiler::Compiler_impl`

class Compiler::CodeGen_impl {
	/**
	 * This entire class object is responsible for only one operation
	 * you should not call `run()` multiple times.*
	 * The correct pipeline flow is:
	 * 1. create buffer
	 * 2. create an object
	 * 3. call run()
	 * 4. use buffer
	 * 
	 * The entire class is a state machine. There will be a lot "global" function call within the scope of the class object
	 */

	/**
	 * all heap allocation here will be temporary. they will be freed after compilation
	 */

	/**
	 * DevNote:
	 * Add reserve
	 * Calculate allocated size after reserve
	 * Assert if current heap capacity is not enough
	 */

	/**
	 * The order of evaluation in implmentation is from right to left
	 * (which is from the back of the array poping back)
	 * All the buffer will reversed. And the new expressions will be appended
	 * after the current expression section, just like stack.
	 */

	/**
	 * Buffers
	 * 
	 * BracketBuffer
	 * Bracket structure generated by BracketParser
	 * Forms a stack like tree structure
	 * Accessability: composed by BracketParser, read only throughout
	 * Lifetime: vector created during compilation, one time init, will be destroied after compilation
	 * Type: compilation data (meta)
	 * 
	 * ConstantBuffer
	 * Store all constant literals / values
	 * Accessability: composed by Tokenlizer, will be write by Compiler for constant pre-evaluatioon
	 * Lifetime: managed by user, exist as span during compilation
	 * Type: compile result data (evaluator usage)
	 * (inside `m_bin`)
	 * 
	 * VariableBuffer
	 * Store the name (std::string_view, source is in `m_source`) of the variables
	 * Accessability: composed by Tokenlizer, forwarding in Compiler
	 * Lifetime: vector created during compilation, ownership will be taken by the user after compilation (in CompileResult)
	 * Type: compile result data (user usage)
	 * DevNote: maybe make my own string_view specificly for this structure to save memory?
	 * 
	 * ExpressionBuffer
	 * Store the expressions (brackets) in a given expression. brackets are represented by their global index in compilation
	 * Acts like stack, and will be constantly appending and deleting.
	 * Accessability: composed by Tokenlizer, read and transfer in Compiler
	 * Lifetime: vector created during compilation, will be destoried after compilation
	 * Type: compilation data (meta)
	 * 
	 * TokenBuffer
	 * Store the tokens generated by Tokenlizer.
	 * Acts like stack, and will be constantly appending and deleting.
	 * Accessability: composed by Tokenlizer, read and transfer in Compiler
	 * Lifetime: vector created during compilation, will be destoried after compilation
	 * Type: compilation data
	 * (reversed)
	 * 
	 * 
	 * Note:
	 * ConstantBuffer and VariableBuffer will accumulate during compilation. 
	 * They will result a structure that have the same sequence as the BracketBuffer.
	 * 
	 * ExpressionBuffer and TokenBuffer will be constantly generating and deleting.
	 * They acts like stack, where the base data will stay, and their child object (expression / bracket) will expand after them.
	 * The processed data will be deleted.
	 * Because the stack like design require them to operate from the back, so in order to
	 * follow normal order of operation (left to right), we need to reverse the tokens for every section (every expression)
	 * And for the expressions, since they do not need traversal, we can just leave them like that
	 */

public:
	CodeGen_impl(
	    std::string_view source,
	    Expression& bin) : m_bin(bin), m_source(source) {}

	// top layer function to be called
	CompileResult run();

private:
	Expression& m_bin;
	std::string_view m_source;

	// buffers

	std::vector<Bracket_impl> m_bracketBuffer;
	std::vector<Variable_impl> m_variableBuffer;
	std::vector<Expression_impl> m_expressionBuffer; // this acts like the stack
	std::vector<Token_impl> m_tokenBuffer; // this acts like stack

	tx::u32 m_constantBufferSize = 0;

	// Sub systems

	// register

	tx::HandleSystemBase<tx::u8> hs;
	tx::u8 registerNew() { return hs.addHandle(); }
	void registerFree(tx::u8 id) { hs.deleteHandle(id); }


	// this is basically the main function of compilation
	void compile_impl();

	// stages

	void stageInit_impl();

	void stageBracket_impl();

	// compilation
	struct StackObject_impl {
		tx::u32
		    expressionIndex,
		    tokenIndex;
		struct Context {
			tx::u32 resultRegister;
			// // if there's no nested expression, these 2 variables will never be used
			// tx::u32 index = tx::InvalidU32; // for the returned expression to resume the previous process
			// tx::u8 expandedExpressionRegister;
		} context;
	};
	inline static constexpr const tx::u8 stackCapacity = tx::u8{ 8 };
	std::array<StackObject_impl, stackCapacity> m_stack; // stores the index of the stack top (end of section) in token
	tx::u32 m_stackPtr = 0;

	// stores the parameter for `handleExpressionExpansion_impl` call
	// Attension: this is not the primary state storage. the stack and token buffer is what store the state
	// see "The state problem - handle expression expansion order problem"
	struct ExpressionContext {
		OperationType_impl operation;
		tx::u8 resultReg; // technically this is already in global (in the stack object), but for the sake of "no brain function call", i'll just keep it here
		bool isFirstMajorExpr;
	} m_context;

	/**
	 * all compile functions will output to the end of m_bin.commandQueue
	 * 
	 * all operations can only apply regarding the current stack object / the stack top
	 * 
	 * ALL INDICES ARE REVERSED within expression. traversal is also reversed
	 * 
	 * The expanding logic:
	 * When a new expression is found in the parent expression, the compilation of the parent expression will be interrupted.
	 * When expanding in the process of compile, it have to make sure that all the context is prepared for the next `compileExpression_impl` call
	 * Additional, it need to save it's own internal state, so that when the expanded expression is done compiling,
	 * it can continue with the value of the expanded expression.
	 * 
	 * Detail:
	 * When encountered a expression:
	 * 1. pop the already processed tokens, including the expression one. but save the operation token before the expression token
	 * 2. push 3 new token: [expressionRegister][operation][majorExpressionRegister]
	 * 		- expressionRegister: the register assigned to the expression
	 * 		- operation: the saved operation before expression
	 * 		- majorExpressionregister: the register of that major expression
	 *			 (major section, the stride of contiuous major operations that was processing by the `compileMajorExpression_impl`
	 * 3. update stack
	 * 4. expand the expression
	 * 
	 * Note: there will not be explicit state saying that it's a resumed expression.
	 * When the `compileMajorExpression_impl` function sees a Register Token, it will just merge it with the current register and then free the token one
	 * Notice that the original major expression's result register will become a temporary value, and get merged with the new result register.
	 * (because it's the first token the resumed function sees, therefore it's value will just be directly assigned to the new result register)
	 * 
	 * Note: though the expression buffer is indeed dynamic, it will not be modified, until it's corresponding parent expression is finished compiling, when the back of it will be deleted
	 * Note: whenever consumed a register token, it must be freed immediatly after
	 * Note: the compilation of each expression should not manage their result register. instead, the parent scope of that expression will have the ownership of that register, and the responsibility of freeing it
	 * 
	 * The lifetime of the major expression register(in the compileExpression_impl -> majorExprReg):
	 * It will be created if the expression is have more then one major expression
	 * It would become the result register of the following major expressions
	 * The value of it will be cleared and overwritten over and over, but it will not be freed, until the current expression is done compiling.
	 * In the case of expanding new expression, it would be written into token cache, then freed by the next iteration, who consumes the value in the register
	 * 
	 * The expanding logic for `compileExpression_impl`
	 * *The above expanding logic is for `compileMajorExpression_impl`.*
	 * Similar to `compileMajorExpression_impl`, `compileExpression_impl` also need to save the state:
	 * - the register that stores the result of the previous processed values (the old resultReg)
	 * - the operator between the old resultReg and the major expression with expansion in it
	 * But different from majorExpression, it does not need to delete tokens,
	 * because that's already done in `compileMajorExpression_impl`, since they share the same token buffer.
	 * 
	 * The state problem - handle expression expansion order problem
	 * `handleExpressionExpansionMajor_impl` does 2 things to the token buffer:
	 * 1. save it's own state
	 * 2. expand the new expression - tokenlize the expression - push more token to the end of the token buffer
	 * But the problem is, after major expression saved it's own state, the upper layer:
	 * the `compileExpression_impl` layer also need to save it's own state, **before expanding the new expression**.
	 * Solution: thanks to the state machine nature of this compiler, we can just put a global context struct that stores the required parameters for the
	 * `handleExpressionExpansion_impl` call, update that context struct everytime before calling `compileMajorExpression_impl`, and call `handleExpressionExpansion_impl` in `handleExpressionExpansionMajor_impl`
	 * And for the `begin` case (`handleExpressionExpansionBegin_impl`) there's no need for it to be called before expansion,
	 * since `handleExpressionExpansionBegin_impl` have nothing to do with the token buffer.
	 * But notice that `handleExpressionExpansionMajorBegin_impl` still need to call `handleExpressionExpansion_impl`, since in the parent scope it might be in the middle
	 * 
	 * Note: all register pushed in the token buffer as register tokens, are becoming temporary registers, and have their lifetime managed by token buffer
	 */

	/**
	 * The major / minor idea
	 * Major operation (multiply and divide), which are evaluate before minor operation
	 * Minor operation (add and subtract), which are evaluate after major operation
	 */

	/**
	 * The rule:
	 * a valid expression must have an odd number of token 
	 * (it stays true in this particular compiler, since:
	 * - barckets are resolved
	 * - expression is folded
	 * - and there's currently no unary operators)
	 */


	// resumable
	// compiles the stack top expression
	// if no expansion required, this function along called one will compile an expression
	// but if expansion happens, then this function will be called to compile the expanded expression;
	// after it's done, this function will be called another time to compile the left over of the parent expression
	// The structure:
	// [majorExpr][minorOp][majorExpr][minorOp][majorExpr]
	// 1. find the minorOp to determind the range of the major expression
	// 2. process the majorExpr
	// 3. goto step 1; when no more minorOp is found (minorPos == end), process one more time for the last majorExpr, and break
	void compileExpression_impl();
	tx::i32 findNextMinorOperator_impl(tx::i32 current, tx::i32 end);
	static bool isMinorOperationToken_impl(Token_impl token) {
		return token.isOperator() &&
		       isMinorOperation_impl(token.getOperatorType());
	}
	static bool isMinorOperation_impl(OperationType_impl operation) {
		return operation == OperationType_impl::Add ||
		       operation == OperationType_impl::Subtract;
	}
	// handles expressionBuffer and stack
	void exitExpression_impl();
	// when the expression expansion triggers, the token layout it like this:
	// [majorExpr (with expansion)] [minorOp (the one minorPos is pointing to)]
	// so what this function need to do:
	// - push an operator token
	// - then push a register token after, which stores the resultReg
	// and for the major expression with expansion, just leave it alone, because `compileMajorExpression_impl` already managed the state
	void handleExpressionExpansion_impl(tx::u8 resultReg, OperationType_impl operation);

	// basically compile a section(which is separated by minor operation)
	// all the compilation happens here
	// after this function returns, the tokens it processed should be deleted
	// @return (boolean) break flag, if true then return
	// @param begin/end [inclusive-exclusive)
	bool compileMajorExpression_impl(tx::i32 begin, tx::i32 end, tx::u8 resultReg);
	// handle expression that's at the front of the parent expression
	void handleExpressionExpansionMajorBegin_impl(
	    Token_impl currentToken,
	    tx::u8 resultReg);
	void handleExpressionExpansionMajor_impl(
	    Token_impl currentToken,
	    tx::i32 current,
	    OperationType_impl operation,
	    tx::u8 resultReg);
	// expand an expression from current context
	// handles stack push and tokenlization
	void expandExpression_impl(Expression_impl expr, tx::u8 resultReg);

	// compilation helpers

	static Token_impl makeOperatorToken_impl(OperationType_impl type) {
		return Token_impl{
			.type = TokenType_impl::Operator,
			.index = static_cast<tx::u8>(type)
		};
	}


	// * stack helpers

	bool stackPush_impl(tx::u32 expressionIndex, tx::u32 tokenIndex, tx::u32 resultRegister) {
		if (m_stackPtr >= stackCapacity) return false; // stack overflow
		m_stack[m_stackPtr] = StackObject_impl{
			.expressionIndex = expressionIndex,
			.tokenIndex = tokenIndex,
			.context = StackObject_impl::Context{ .resultRegister = resultRegister }
		};
		m_stackPtr++;
		return true;
	}
	void stackPop_impl() {
		m_stackPtr--;
	}

	// the current stack object
	StackObject_impl& stackTop_impl() { return m_stack[m_stackPtr - 1]; }
	StackObject_impl& stackParent_impl() { return m_stack[m_stackPtr - 2]; }


	// helpers

	// * tokenlizer parameter

	std::string_view findBracketSource_impl(Bracket_impl bracket) const {
		return m_source.substr(
		    bracket.range.offset + 1,
		    bracket.range.size - 2);
	}
	tx::u32 findBracketSourceOffset_impl(Bracket_impl bracket) const {
		return bracket.range.offset + 1;
	}
	std::span<const Bracket_impl> findBracketChilds_impl(Bracket_impl bracket) const {
		return std::span<const Bracket_impl>{
			m_bracketBuffer.begin() + (bracket.index + 1),
			m_bracketBuffer.begin() + (bracket.index + 1 + bracket.childCount)
		};
	}

	void tokenlize_impl(
	    std::string_view source,
	    tx::u32 sourceOffset,
	    std::span<const Bracket_impl> bracketBuffer);
	// somewhat high level helper function
	void tokenlize_impl(Bracket_impl bracket);

	// code gen

	tx::u32 m_commandBufferSize = 0;
	void pushCommand_impl(
	    tx::u8 dest,
	    OperationType_impl operation,
	    tx::u8 vala,
	    tx::u8 valb);
	tx::u8 makeValueID_impl(tx::u8 index, bool isFromBuffer, bool isVariableBuffer = false) {
		return tx::bit::set_copy(
		    tx::bit::set_copy(index, tx::u8{ 0x80 }, isFromBuffer),
		    tx::u8{ 0x40 }, isVariableBuffer);
	}
};
} // namespace tx::csl